"""Plot the JSON exported from the app's actual C# mesh generator."""
import json
import os
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / '.cache' / 'plotting'))
os.environ.setdefault('MPLCONFIGDIR', str(ROOT / '.cache' / 'matplotlib'))
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
from matplotlib.collections import LineCollection
from mpl_toolkits.mplot3d.art3d import Poly3DCollection
import numpy as np


def main():
    folder = ROOT / 'artifacts' / 'geometry'
    fig = plt.figure(figsize=(15, 9), facecolor='#f6f7f5')
    fig.text(.055, .95, 'The meshes we can test today', fontsize=25, weight='bold', color='#163d3a')
    fig.text(.055, .91, 'Generated by the app’s C# geometry code · dimensions and UV coordinates in centimetres', fontsize=12)
    metrics = []
    for column, name in enumerate(('plane', 'box', 'cylinder')):
        data = json.loads((folder / f'{name}.json').read_text())
        p = np.array(data['positions'], dtype=float)
        n = np.array(data['normals'], dtype=float)
        uv = np.array(data['uvMetres'], dtype=float)
        tri = np.array(data['triangles']).reshape(-1, 3)
        cross = np.cross(p[tri[:, 1]] - p[tri[:, 0]], p[tri[:, 2]] - p[tri[:, 0]])
        alignment = np.sum(cross * n[tri].mean(axis=1), axis=1)
        metric = {'shape': name, 'vertices': len(p), 'triangles': len(tri),
                  'boundsMetres': (p.max(axis=0)-p.min(axis=0)).tolist(),
                  'maxNormalLengthError': float(np.max(np.abs(np.linalg.norm(n, axis=1)-1))),
                  'minOutwardWindingDot': float(alignment.min())}
        if name == 'cylinder':
            radius = np.linalg.norm(p[:194, [0, 2]], axis=1)
            metric['maxSideRadiusErrorMetres'] = float(np.max(np.abs(radius-.05)))
            metric['sideUVWidthMetres'] = float(uv[:194, 0].max()-uv[:194, 0].min())
        metrics.append(metric)
        ax = fig.add_subplot(2, 3, column+1, projection='3d', facecolor='#f6f7f5')
        # Unity is Y-up. Reorder only for the plot's vertical axis.
        plotted = p[:, [0, 2, 1]] * 100
        faces = Poly3DCollection(plotted[tri], facecolors='#85c7ba', edgecolors='#226c62',
                                 linewidths=.35 if name == 'cylinder' else .8, alpha=.6)
        ax.add_collection3d(faces)
        for axis, extent in enumerate(((-8, 8), (-8, 8), (0, 21))):
            (ax.set_xlim, ax.set_ylim, ax.set_zlim)[axis](*extent)
        ax.set_box_aspect((16, 16, 21))
        ax.view_init(elev=23, azim=-55)
        ax.set_xlabel('X (cm)', fontsize=9)
        ax.set_ylabel('Z (cm)', fontsize=9)
        ax.set_zlabel('Y (cm)', fontsize=9)
        ax.tick_params(labelsize=8)
        ax.set_title(f'{name.title()}  |  {len(p)} vertices · {len(tri)} triangles', fontsize=12, weight='bold')
        ax2 = fig.add_subplot(2, 3, column+4, facecolor='white')
        edges = []
        for face in tri:
            edges.extend([(uv[face[i]]*100, uv[face[(i+1)%3]]*100) for i in range(3)])
        ax2.add_collection(LineCollection(edges, colors='#226c62', linewidths=.35, alpha=.7))
        ax2.autoscale()
        ax2.set_aspect('equal', adjustable='box')
        ax2.set_xlabel('U distance (cm)', fontsize=10)
        ax2.set_ylabel('V distance (cm)', fontsize=10)
        ax2.set_title('Metric UV layout', fontsize=11)
        ax2.grid(alpha=.15)
        ax2.tick_params(labelsize=9)
    fig.subplots_adjust(left=.055, right=.97, top=.85, bottom=.17, wspace=.3, hspace=.3)
    fig.text(.055, .105, 'Verified: nondegenerate triangles, outward winding, unit normals, physical dimensions and cylinder seam.', fontsize=11)
    fig.text(.055, .068, 'SOURCE GEOMETRY ONLY — camera alignment, shading, occlusion and drift still need Unity + phone testing.',
             fontsize=11, weight='bold', color='#9a521f')
    fig.savefig(folder / 'geometry-report.png', dpi=140)
    (folder / 'metrics.json').write_text(json.dumps(metrics, indent=2) + '\n')
    print(json.dumps(metrics, indent=2))


if __name__ == '__main__':
    main()
